apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: privacera-dataserver
  name: privacera-dataserver
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: privacera-dataserver
    spec:
      initContainers:
      - name: copy
        image: hub2.privacera.com/privacera_dataserver:rel_ds_2.0
        command: ["bash", "-c", "cp -r /conf_ro/. /conf"]
        volumeMounts:
        - mountPath: /conf_ro
          name: privacera-dataserver-config-vol 
        - mountPath: /conf
          name: data
      imagePullSecrets:
      - name: regcred
      containers:
      - image: hub2.privacera.com/privacera_dataserver:rel_ds_2.0
        name: privacera-dataserver
        ports:
        - containerPort: 8181
        - containerPort: 8282
        - containerPort: 9191
        - containerPort: 9292
        resources: {}
        volumeMounts:
        - mountPath: /workdir/privacera-data-server/conf 
          name: data 
      restartPolicy: Always
      volumes:
      - name: data
        emptyDir: {}
      - name: privacera-dataserver-config-vol
        configMap:
            name: {{ .Release.Name }}-dataserver-cm-conf
#      - name: privacera-dataserver-claim0
#        persistentVolumeClaim:
#          claimName: privacera-dataserver-claim0
status: {}
