apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/paresh/sw/kompose convert
    kompose.version: 1.17.0 (a74acad)
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: privacera-dataserver
  name: privacera-dataserver
spec:
  ports:
  - name: "8181"
    port: 8181
    targetPort: 8181
  - name: "8282"
    port: 8282
    targetPort: 8282
  - name: "9191"
    port: 9191
    targetPort: 9191
  - name: "9292"
    port: 9292
    targetPort: 9292
  selector:
    io.kompose.service: privacera-dataserver
  type: LoadBalancer
status:
  loadBalancer: {}
