apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: portal-1 
  name: portal-1
  annotations:
{{- with .Values.portal }}
    service.beta.kubernetes.io/aws-load-balancer-internal: {{ .internal | quote }}
spec:
  ports:
  - name: {{ .port | quote }}
    port: {{ .port }}
    targetPort: {{ .port }}
{{- end }}
  selector:
    io.kompose.service: portal-1
  type: LoadBalancer
status:
  loadBalancer: {}
