apiVersion: v1
kind: Service
metadata:
  name: zkensemble
  labels:
    app: zookeeper-app
spec:
  clusterIP: None
  selector:
    app: zookeeper-app
---
apiVersion: v1
kind: Service
metadata:
  name: zk-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  labels:
    app: zookeeper-app
spec:
  ports:
  - protocol: TCP
{{- with .Values.zk }}
    port: {{ .port }}
    targetPort: {{ .port }}
{{- end }}
  type: LoadBalancer
  selector:
    app: zookeeper-app
