kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  #name: {{ .Release.Name }}-store-zkensemble
  name: portal-store-zkensemble
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  fsType: ext4
  type: gp2
#  fsType: xfs
#  location: eastus
#  storageAccount: azure_storage_account_name
