apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ranger
  name: ranger
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "{{ .Values.ranger.internal }}"
spec:
  ports:
  - name: "6080"
    port: 6080
    targetPort: 6080
  selector:
    io.kompose.service: ranger
  type: LoadBalancer
status:
  loadBalancer: {}
